package co.jp.javademoproject.part4.part4_6_exception;

public class ExceptionIntro2 {
    public static void main(String[] args) {

        // 数学上的异常 除0操作
//        int b = 10;
//        try {
//            // 读文件 不读一读 不知道
//            // 发生异常的时候 异常发生点 以下是不会被执行的
//            // 1
//            // 2 exception
//            // 3 没执行
//            // 4 没执行
//        } catch (SqlException ae) {
//            // 成功的情况下 catch不会被执行
//            // ae.printStackTrace();
//            b = 100;
//        }
//        System.out.println("b : " + b);
    }
}
